
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5555/trackme-auth-db
    username: admin
    password: ENC(P/mTks+sO+MKVPFW4JaKh7nvZERQ2lfu)
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ENC(vsphGaygBANGokzkd30owPBUe+q6apyJ)

jasypt:
  encryptor:
    password: trackme-secretkey
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

verification:
  token:
    expiry: 86400000