server:
  port: 8060

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://host.docker.internal:5555/trackme-auth-db
    username: admin
    password: ENC(P/mTks+sO+MKVPFW4JaKh7nvZERQ2lfu)
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
#      the below is needed for docker, HOST variable is passed in docker compose
  instance:
    prefer-ip-address: true
    ip-address: "${HOST}"
jwt:
  secret: ENC(vsphGaygBANGokzkd30owPBUe+q6apyJ)

jasypt:
  encryptor:
    password: trackme-secretkey
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator