
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5555/trackme-auth-db
    username: admin
    password: ENC(oV9bkFo5UOAl9tnpsOj0HEn4B1hGhYw+l5D7FfCEEIY=)
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    generate-ddl: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ENC(tpN5k5aIW1HYEapi+hlvVOTObuZ4feb+TQsErlUHgk0=)