spring:
  application:
    name: api-gateway
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 60000


#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds:  60000
#
#ribbon:
#    ConnectTimeout: 10000
#    ReadTimeout: 10000