spring:
  application:
    name: central-config
  profiles:
    active: dev, test, prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MichaelAbouKhalil/TrackMe
          clone-on-start: true
          search-paths:
            - 'trackme-conf'
            - 'trackme-conf/*'
            - 'trackme-conf/**'
          default-label: master
server:
  port: 8888
